# server config
server:
  ip: 127.0.0.1
  port: 8081
# mysql config
mysql:
  user: root
  password: WJGUchenwei2000
  address: 124.70.201.39
  port: 3306
  dbname: check_in_sys
  config: charset=utf8&parseTime=True&loc=Local
# redis config
redis:
  address: 124.70.201.39:6379
  password: 200010
# log config
log:
  filepath: log/log.log
mail:
  address: lutasam@sina.com
  username: lutasam
  host: smtp.sina.com
  auth: c521392a5189032a
file:
  imgs:
    address: /share/public/imgs/
    # linux: /share/public/imgs/
    # Windows: imgs/
    url: http://124.70.201.39:8080/imgs/
    # linux: http://124.70.201.39:8080/imgs/
    # Windows: D:/Code/program/Go/src/gin_admin_sys/imgs/
  files:
    address: /share/public/files/
    # linux: /share/public/files/
    # Windows: files/